### ISSUE TITLE
very nice sample 

### ISSUE THREAD

**Issue by RakeshShrestha** [checkdigits/How_to_Create_a_News_App_with_Delphi_Firemonkey_example#1]
The sample is very good for beginners .. it would have been great if this sample can be replicated in c++ builder also ..

**Comment by MuminjonGuru** [comment]
There will be one :)

**Comment by RakeshShrestha** [comment]
did u replicate .. i am looking for it

**Comment by checkdigits** [comment]
Sorry, not yet. Look out on https://blogs.embarcadero.com and https://learncplusplus.org for news when we have one.
